import type { Meta, StoryObj } from "@storybook/react";
import { Button } from "./button";
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Primary: Story;
export declare const PrimaryLarge: Story;
export declare const Danger: Story;
export declare const DangerSmall: Story;
export declare const PrimaryOutline: Story;
export declare const SquareDanger: Story;
export declare const SquareDangerOutline: Story;
export declare const Loading: Story;
export declare const LoadingCustom: Story;
export declare const LoadingSpinner: Story;
export declare const Disabled: Story;
export declare const PrimaryLink: Story;
