name: Build SCSS

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Build SCSS
        run: yarn workspace @inventare/styles build
