name: Publish Packages

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn

      - name: Build SCSS
        run: yarn workspace @inventare/styles build

      - name: Build React
        run: yarn workspace @inventare/react build

      - name: Publish Package to NPM
        run: yarn publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
