name: Build on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Test Packages"
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: yarn workspace @inventare/vanilla test

  build:
    name: "Build Packages"
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Turbo Build
        run: yarn build
