name: Build on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Test Packages"
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: yarn test

  build:
    name: "Build Packages"
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Turbo Build
        run: yarn build

  docs:
    name: "Build Documentation"
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Build Packages
        run: yarn build

      - name: Build Documentation
        run: yarn build:docs
