name: Build on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build Styles and React Lib"
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Build SCSS
        run: yarn workspace @inventare/styles build
