name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: yarn workspace @inventare/docs storybook:docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY }}
          publish_dir: ./apps/docs/storybook-static
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
